let zp = Number(prompt("Enter your zp"))
alert(zp)
let zpwithprem = Number(zp*0.15+zp)
alert (zpwithprem)
let zppremnal= Number(zpwithprem *0.1)
alert (zppremnal)
let trata = Number (zpwithprem - zppremnal - 190)
alert (trata)
let mj= (trata / 2)
alert  (mj) 